import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children,params }) {
  return (
    <html>
      <body className={inter.className} dir="ltr" cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  )
}
